### ISSUE TITLE
您好，请问有测试的源码吗

### ISSUE THREAD

**Issue by fubai3** [kadoufall/Image-Super-Resolution-VS#1]
有的话帮忙给我发一下，谢谢。

**Comment by kadoufall** [comment]
> 有的话帮忙给我发一下，谢谢。

我没有写单独的测试文件，现在的测试是在每一轮训练后测试的，代码是`isr_train.py`下的[generate_and_save_images](https://github.com/kadoufall/Image-Super-Resolution-VS/blob/master/image-super-resolution/isr_train.py#L68)

**Comment by fubai3** [comment]
好的，谢谢
